site_name: The No-Nonsense Basic JavaScript Guide for the Novice Web Developer
site_author: Aliya N. Anindita
theme: readthedocs
nav:
    - Home: 'index.md'
    - The Guide:
        - "Basic Concepts": 'js-concept.md'
        - "Inserting JavaScript": 'inserting-js.md'
        - "Getting and Manipulating Elements": 'get-set.md'
        - "Events": 'events.md'
        - "Form Shenanigans": 'handling-forms.md'
        - "Animating with Transition": 'transition.md'
        - "Timing": 'timing.md'
        - "Advanced Elements Manipulation": "get-set-advanced.md"
        - "Frameworks and Libraries": 'frameworks.md'
        - "Afterwords": 'thatsall.md'
    - Appendix:
        - "Which part of this is no-nonsense anyway?": "whatnononsense.md"
        - "Really Quick Guide to Programming with JavaScript": 'js-quickguide.md'
        - "Guestbook": 'guestbook.md'
    